driver:
  name: docker
  use_sudo: false

platforms:
  - name: debian-7

<% %w(12.04 14.04).each do |ubver| %>
  - name: ubuntu-<%= ubver %>
    driver:
      platform: ubuntu
      forward: 80
      publish_all: true
      image: ubuntu-upstart:<%= ubver %>
      disable_upstart: false
      run_command: /sbin/init
<% end %>
